# Site settings
title: Fast Monkeys Github
email: contact@fastmonkeys.com
description: "Popular git repositories from some of the people of Fast Monkeys."
baseurl: ""
url: "http://fastmonkeys.github.io"
username: "FastMonkeys"

# Build settings
markdown: kramdown
permalink: pretty
